### ISSUE TITLE
RegisterItem.PHP

### ISSUE THREAD

**Issue by rshariffdeen** [sguazt/RUBiS#1]
Both variables duration and buyNow are not read from the request. 
There is a mismatch in $quantity in the insert statement where you have read it as $qty

**Comment by sguazt** [comment]
Hi,

For the first issue, could you be more specific?
In `RegisterItem.php`, variables `$duration` and `$buyNow` are read from request with a code like the following:

``` php
    $var = NULL;
    if (isset($_POST['param'])) {
        $var = $_POST['param'];
    } else if (isset($_GET['param']))  {
        $var = $_GET['param'];
    } else {
        printError(...);
        exit();
    }
```

See line 89 for `$buyNow` and line 93 for `$duration`.
So, what's wrong?

For the second issue, I think you're referring to the `$quantity` variable in the error message of the INSERT statement (line 141), do you?
If so, yes it is a typo and I will fix it. If not, please provide more details.

Cheers.
Marco

**Comment by rshariffdeen** [comment]
Hi,
Apparently I have mistaken it with the original. Yes I did mention about the typo

Regards

**Comment by sguazt** [comment]
Fixed
